const songs = [
  {
    id: "1",
    title: "Tình sầu",
    album: "Em và Trịnh",
    year: "2022",
    url: require("./tinh-sau.mp3"),
    // imageUrl: require("./tinh-sau.jpg"),
  },
  {
    id: "2",
    title: "The way that I love you",
    album: "Songs for the Drunk and Broken Hearted",
    year: "2021",
    url: require("./the-way-that-i-love-you.mp3"),
    // imageUrl: require("./tinh-sau.jpg"),
  },
  {
    id: "3",
    title: "Người hãy quên em đi",
    album: "Tâm 9",
    year: "2017",
    url: require("./nguoi-hay-quen-em-di.mp3"),
    // imageUrl: require("./tinh-sau.jpg"),
  },
  {
    id: "4",
    title: "Giữa đại lộ Đông Tây",
    album: null,
    year: "2021",
    url: require("./giua-dai-lo-Dong-Tay.mp3"),
    // imageUrl: require("./tinh-sau.jpg"),
  },
  {
    id: "5",
    title: "Date 2",
    album: "Your Name",
    year: "2016",
    url: require("./Date-2.mp3"),
    // imageUrl: require("./tinh-sau.jpg"),
  },
  {
    id: "6",
    title: "STAY",
    album: "SQUARE TWO",
    year: "2016",
    url: require("./STAY.mp3"),
    // imageUrl: require("./tinh-sau.jpg"),
  },
];
export default songs;
